check cluster

diff --git a/argparse b/argparse
--- a/argparse
+++ b/argparse
@@ -129,4 +129,12 @@ then
 fi
 CLUSTER=$_arg_cluster
 
+source $(dirname $0)/utils.sh
+SLURM_PORT="$(find_port "$CLUSTER")"
+if [ -z "$SLURM_PORT" ]
+then
+    echo "[Error] cluster name $CLUSTER not found in config" >> /dev/stderr
+    exit 1
+fi
+
 # ] <-- needed because of Argbash
